# Generated by Django 5.2.8 on 2026-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0017_apontamento_id_agrupamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apontamento',
            name='flag_atencao',
            field=models.BooleanField(default=False, verbose_name='Atenção/Conformidade'),
        ),
        migrations.AddField(
            model_name='apontamento',
            name='motivo_alerta',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Alerta'),
        ),
    ]
