# Generated by Django 5.2.8 on 2026-01-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0018_apontamento_flag_atencao_apontamento_motivo_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamento',
            name='flag_atencao',
            field=models.BooleanField(default=False, verbose_name='Atenção Conformidade'),
        ),
    ]
