# Generated by Django 5.2.8 on 2026-01-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0019_alter_apontamento_flag_atencao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('tipo', models.CharField(choices=[('ALERTA', 'Alerta de Conformidade'), ('INFO', 'Informativo Geral'), ('SUCESSO', 'Conclusão de Processo')], default='INFO', max_length=10)),
                ('lida', models.BooleanField(default=False, verbose_name='Lida?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='produtividade.colaborador', verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
