# Generated by Django 5.2.8 on 2026-01-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0020_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='comentario_colaborador',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta/Justificativa'),
        ),
    ]
