# Generated by Django 5.2.8 on 2026-01-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0021_notificacao_comentario_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='data_referencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Referência (Para Alertas)'),
        ),
    ]
