# Generated by Django 5.2.8 on 2026-02-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0022_notificacao_data_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(blank=True, help_text='Necessário para cálculo de feriados municipais', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='uf',
            field=models.CharField(blank=True, help_text='Sigla do Estado (ex: SP, RJ)', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='FeriadoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Feriado')),
                ('descricao', models.CharField(max_length=100, verbose_name='Nome do Feriado')),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Feriado Municipal',
                'verbose_name_plural': 'Feriados Municipais',
                'unique_together': {('data', 'cidade', 'uf')},
            },
        ),
    ]
