# Generated by Django 5.2.8 on 2026-02-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0023_colaborador_cidade_colaborador_uf_feriadomunicipal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeriadoMunicipal',
            new_name='Feriado',
        ),
        migrations.AlterModelOptions(
            name='feriado',
            options={'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
    ]
