# Generated by Django 5.2.8 on 2026-02-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0024_rename_feriadomunicipal_feriado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Login / Acesso'), ('LOGOUT', 'Logout / Saída'), ('CRIACAO', 'Criação de Registro'), ('EDICAO', 'Edição de Registro'), ('EXCLUSAO', 'Exclusão de Registro'), ('APROVACAO', 'Aprovação de Gestor'), ('REJEICAO', 'Rejeição de Gestor'), ('EXPORTACAO', 'Exportação de Dados')], max_length=20)),
                ('modelo_afetado', models.CharField(max_length=50, verbose_name='Módulo/Tabela')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Objeto')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes da Ação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
