# Generated by Django 5.2.8 on 2026-02-05 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0025_logauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: 19987654321', max_length=20, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login / Acesso'), ('LOGOUT', 'Logout / Saída'), ('CRIACAO', 'Criação de Registro'), ('EDICAO', 'Edição de Registro'), ('EXCLUSAO', 'Exclusão de Registro'), ('APROVACAO', 'Aprovação de Apontamento'), ('REJEICAO', 'Rejeição de Apontamento'), ('SOLICITACAO', 'Solicitação de Ajuste'), ('APROVACAO_AJUSTE', 'Aprovação de Ajuste'), ('EXPORTACAO', 'Exportação de Dados')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['data_hora', 'acao'], name='produtivida_data_ho_9f4d8c_idx'),
        ),
    ]
