# Generated by Django 5.2.8 on 2026-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtividade', '0026_colaborador_telefone_alter_logauditoria_acao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamento',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Término'),
        ),
    ]
